name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    if: false
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan PHP & JS dependencies
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          format: 'table'
          scanners: 'vuln,secret'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
          exit-code: '0' # set to 1 to terminate build

      - name: Build an image from Dockerfile
        run: |
          docker build ./docker/8.2/ -t ${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: ${{ github.sha }}
          format: 'table'
          exit-code: '0'  # set to 1 to terminate build
          vuln-type: 'os,library'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Check Sonar Status
        uses: sonarcloud-actions/sonarcloud-check-status-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
