name: larastan
on:
  push:
    branches:
      - main
jobs:
  larastan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: "dom, curl, libxml, mbstring, zip, fileinfo"
          coverage: "none"

      - name: Install Larastan
        run: composer require nunomaduro/larastan:^2.0 --dev --no-update --no-interaction --no-progress

      - name: Debug
        run: ls -la

      - name: Run Larastan
        run: composer run-script phpstan
