name: larastan
on:
  push:
    branches:
      - main
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run larastan
        run: |
          php -v
          composer -v
