name: larastan
on:
  push:
    branches:
      - main
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: "dom, curl, libxml, mbstring, zip, fileinfo"
          coverage: "none"

      - name: Install Larastan
        run: composer install nunomaduro/larastan --no-interaction --no-progress

      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse --ansi --memory-limit 256M
